### ISSUE TITLE
Make bar chart same height as the other charts

### ISSUE THREAD

**Issue by PeterRydberg** [dotkom/gradestats-app#74]
**Is your feature request related to a problem? Please describe.**
This _may_ be a bug, but iunno. The bar chart doesn't have the same visual height as the other chart types.

**Describe the solution you'd like**
Make it heightier. That's not a word.

**Describe alternatives you've considered**
The lines themselves are what dictates perception of height of the component, so I guess the lines should be stretched to the same height as the others. I see that @aslakhol suggested in #72 that they should be removed, which is also a possible solution. If that is the case, the bars should be normalized so you always have one bar that uses the full height of the chart.

Alternatively, create lines on the left _and_ right side of each bar, then stretch them to the top. It might be more visually consistent with the other charts.

Just for clarification, when I say visually consistent height I mean that the bottom line and top line should be in the same place for all charts, giving the perception that they are of the same size.

**Additional context**
Professional illustration (using the CSS from #71):
![image](https://user-images.githubusercontent.com/22096301/104735781-51fe2400-5742-11eb-826b-3e7053df5a6f.png)
![image](https://user-images.githubusercontent.com/22096301/104736513-5ecf4780-5743-11eb-8fc1-9e6b546b9c45.png)

**Comment by oleast** [comment]
This has been fixed, by #89 and #79 or something, don't remember. What do you think?

**Comment by PeterRydberg** [comment]
Hmmm. I think the height looks good, but the chart still seems a little visually inconsistent with the other two. I'd want to make sure start and end of the bottom chart line lines up with the left and right bars respectively. Like the one badly drawn in my image. If that's even possible with the library you're using?

![image](https://user-images.githubusercontent.com/22096301/105356786-22dd2c00-5bf4-11eb-8c62-592ab819e9f3.png)
